---- DTS
CREATE OR REPLACE TABLE ETL.DTS.DTS
AS 
    SELECT
		_FIVETRAN_ID
		,TRACKINGSTATUSLABEL
		,CLOSEID
		,ALTTRACKINGNUMBER
		,CAST(PACKAGEITEMTOTALQUANTITY AS FLOAT) PACKAGEITEMTOTALQUANTITY
		,ACCOUNTNUMBER
		,CAST(CHANNELID AS FLOAT) CHANNELID
		,BASECARRIERCODE
		,CARRIERINSURANCECHARGE
		,MARKETID
		,HOST
		,ORIGINCOMPANY
		,DIMLENGTH
		,ESTIMATEDDELIVERYDATE
		,CUSTOMID
		,SHIPTOADDRESS3
		,SHIPZONE
		,SHIPTOADDRESS2
		,CARRIER
		,PACKAGECHARGEATRATING
		,SHIPTOADDRESS1
		,BOXNAME
		,SUBACCOUNTNUMBER
		,CAST(ORDERID AS FLOAT) ORDERID
		,STATUS
		,CARRIERBILLINGTYPE
		,SHIPTYPE
		,SURCHARGECHARGE
		,APPLIEDCHARGETYPE
		,USERNAME
		,ID
		,WORKSTATION
		,TRACKINGEVENTDATE
		,CUSTOMREF2
		,CUSTOMREF3
		,SHIPTOCITY
		,PRIVATEINSURANCEAMOUNT
		,LASTPRINTDATE
		,MARKETSHIPMETHOD
		,DRYICEWEIGHT
		,ORDERTYPE
		,CREATEDATE
		,TRACKINGEVENTDESCRIPTION
		,SHIPTOSTATEORPROVINCE
		,FUELCHARGE
		,ORIGINSTATEORPROVINCE
		,DEPARTMENT
		,PRIVATEINSURANCECHARGE
		,BATCHID
		,DELIVERYAREACHARGE
		,CURRENCYCODEISO
		,CAST(STATUSID AS FLOAT) STATUSID
		,ORIGINCITY
		,ACTUALWEIGHT
		,CAST(ORDERCOUNT AS FLOAT) ORDERCOUNT
		,CARRIERINSURANCEAMOUNT
		,SHIPTOCOMPANY
		,UPDATEDATE
		,SHIPROUTE
		,CAST(SHIPPINGPROFILEID AS FLOAT) SHIPPINGPROFILEID
		,CUSTOMREF1
		,TOTALCHARGE
		,USPSPROVIDERTYPE
		,TRACKINGEVENTLOCATION
		,ORIGINADDRESS1
		,SHIPTOPOSTALCODE
		,CAST(CHANNELLINKID AS FLOAT) CHANNELLINKID
		,SATURDAYDELIVERYCHARGE
		,ORIGINADDRESS2
		,SHIPPEDWEIGHT
		,SHIPCHARGE
		,ORIGINPOSTALCODE
		,ORDERNUMBER
		,DRYICECHARGE
		,CAST(TRACKINGSTATUSID AS FLOAT) TRACKINGSTATUSID
		,REFERENCEID
		,SIGNATUREREQUIREDCHARGE
		,TRACKINGNUMBER
		,RETURNRECEIPTCHARGE
		,CREATED_DTTM
		,DIMHEIGHT
		,DELIVERYCONFIRMATIONCHARGE
		,LABELTYPE
		,RESIDENTIALAREACHARGE
		,SHIPTOCONTACT
		,DIMMEDWEIGHT
		,MARKETREFERENCE
		,SHIPTOCOUNTRYCODE
		,HANDLINGCHARGE
		,ORIGINCOUNTRYCODE
		,HAZARDOUSMATERIALSCODE
		,CAST(TABLEID AS FLOAT) TABLEID
		,DIMWIDTH
		,CARRIERVERSIONFLAG
		,BASECARRIERTYPE
		,ORIGINCOUNTRY
		,RESTRICTEDDELIVERYCHARGE
		,_FIVETRAN_DELETED
		,_FIVETRAN_SYNCED
		,BILLINGACCOUNTNUMBER        
		FROM XBPRDWMGOLD.PRD_GOLD_GC_XBWM19WM.DTS_DATA_WAREHOUSE DTS_DATA_WAREHOUSE

        UNION
        
		SELECT
		_FIVETRAN_ID
		,TRACKINGSTATUSLABEL
		,CLOSEID
		,ALTTRACKINGNUMBER
		,CAST(PACKAGEITEMTOTALQUANTITY AS FLOAT) PACKAGEITEMTOTALQUANTITY
		,ACCOUNTNUMBER
		,CAST(CHANNELID AS FLOAT) CHANNELID
		,BASECARRIERCODE
		,CARRIERINSURANCECHARGE
		,MARKETID
		,HOST
		,ORIGINCOMPANY
		,DIMLENGTH
		,ESTIMATEDDELIVERYDATE
		,CUSTOMID
		,SHIPTOADDRESS3
		,SHIPZONE
		,SHIPTOADDRESS2
		,CARRIER
		,PACKAGECHARGEATRATING
		,SHIPTOADDRESS1
		,BOXNAME
		,SUBACCOUNTNUMBER
		,CAST(ORDERID AS FLOAT) ORDERID
		,STATUS
		,CARRIERBILLINGTYPE
		,SHIPTYPE
		,SURCHARGECHARGE
		,APPLIEDCHARGETYPE
		,USERNAME
		,ID
		,WORKSTATION
		,TRACKINGEVENTDATE
		,CUSTOMREF2
		,CUSTOMREF3
		,SHIPTOCITY
		,PRIVATEINSURANCEAMOUNT
		,LASTPRINTDATE
		,MARKETSHIPMETHOD
		,DRYICEWEIGHT
		,ORDERTYPE
		,CREATEDATE
		,TRACKINGEVENTDESCRIPTION
		,SHIPTOSTATEORPROVINCE
		,FUELCHARGE
		,ORIGINSTATEORPROVINCE
		,DEPARTMENT
		,PRIVATEINSURANCECHARGE
		,BATCHID
		,DELIVERYAREACHARGE
		,CURRENCYCODEISO
		,CAST(STATUSID AS FLOAT) STATUSID
		,ORIGINCITY
		,ACTUALWEIGHT
		,CAST(ORDERCOUNT AS FLOAT) ORDERCOUNT
		,CARRIERINSURANCEAMOUNT
		,SHIPTOCOMPANY
		,UPDATEDATE
		,SHIPROUTE
		,CAST(SHIPPINGPROFILEID AS FLOAT) SHIPPINGPROFILEID
		,CUSTOMREF1
		,TOTALCHARGE
		,USPSPROVIDERTYPE
		,TRACKINGEVENTLOCATION
		,ORIGINADDRESS1
		,SHIPTOPOSTALCODE
		,CAST(CHANNELLINKID AS FLOAT) CHANNELLINKID
		,SATURDAYDELIVERYCHARGE
		,ORIGINADDRESS2
		,SHIPPEDWEIGHT
		,SHIPCHARGE
		,ORIGINPOSTALCODE
		,ORDERNUMBER
		,DRYICECHARGE
		,CAST(TRACKINGSTATUSID AS FLOAT) TRACKINGSTATUSID
		,REFERENCEID
		,SIGNATUREREQUIREDCHARGE
		,TRACKINGNUMBER
		,RETURNRECEIPTCHARGE
		,CREATED_DTTM
		,DIMHEIGHT
		,DELIVERYCONFIRMATIONCHARGE
		,LABELTYPE
		,RESIDENTIALAREACHARGE
		,SHIPTOCONTACT
		,DIMMEDWEIGHT
		,MARKETREFERENCE
		,SHIPTOCOUNTRYCODE
		,HANDLINGCHARGE
		,ORIGINCOUNTRYCODE
		,HAZARDOUSMATERIALSCODE
		,CAST(TABLEID AS FLOAT) TABLEID
		,DIMWIDTH
		,CARRIERVERSIONFLAG
		,BASECARRIERTYPE
		,ORIGINCOUNTRY
		,RESTRICTEDDELIVERYCHARGE
		,_FIVETRAN_DELETED
		,_FIVETRAN_SYNCED
		,BILLINGACCOUNTNUMBER
		FROM DTS.DTS_XBWM19WM.DTS_DATA_WAREHOUSE DTS_DATA_WAREHOUSE
        WHERE ID NOT IN (SELECT ID FROM XBPRDWMGOLD.PRD_GOLD_GC_XBWM19WM.DTS_DATA_WAREHOUSE) 
        
        ;

---------------------- SP DTS
SELECT COUNT(*) FROM ETL.DTS.DTS;
CALL ETL.DTS.SP_UPDATE_ETL_DTS();

32475298;

CREATE OR REPLACE PROCEDURE ETL.DTS.SP_UPDATE_ETL_DTS()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER 
AS
BEGIN 
    MERGE INTO ETL.DTS.DTS AS TARGET
    USING (
        SELECT 
            _FIVETRAN_ID, TRACKINGSTATUSLABEL, CLOSEID, ALTTRACKINGNUMBER,
            CAST(PACKAGEITEMTOTALQUANTITY AS FLOAT) AS PACKAGEITEMTOTALQUANTITY,
            ACCOUNTNUMBER, CAST(CHANNELID AS FLOAT) AS CHANNELID,
            BASECARRIERCODE, CARRIERINSURANCECHARGE, MARKETID, HOST,
            ORIGINCOMPANY, DIMLENGTH, ESTIMATEDDELIVERYDATE, CUSTOMID,
            SHIPTOADDRESS3, SHIPZONE, SHIPTOADDRESS2, CARRIER,
            PACKAGECHARGEATRATING, SHIPTOADDRESS1, BOXNAME, SUBACCOUNTNUMBER,
            CAST(ORDERID AS FLOAT) AS ORDERID, STATUS, CARRIERBILLINGTYPE,
            SHIPTYPE, SURCHARGECHARGE, APPLIEDCHARGETYPE, USERNAME, ID,
            WORKSTATION, TRACKINGEVENTDATE, CUSTOMREF2, CUSTOMREF3,
            SHIPTOCITY, PRIVATEINSURANCEAMOUNT, LASTPRINTDATE, MARKETSHIPMETHOD,
            DRYICEWEIGHT, ORDERTYPE, CREATEDATE, TRACKINGEVENTDESCRIPTION,
            SHIPTOSTATEORPROVINCE, FUELCHARGE, ORIGINSTATEORPROVINCE,
            DEPARTMENT, PRIVATEINSURANCECHARGE, BATCHID, DELIVERYAREACHARGE,
            CURRENCYCODEISO, CAST(STATUSID AS FLOAT) AS STATUSID, ORIGINCITY,
            ACTUALWEIGHT, CAST(ORDERCOUNT AS FLOAT) AS ORDERCOUNT,
            CARRIERINSURANCEAMOUNT, SHIPTOCOMPANY, UPDATEDATE, SHIPROUTE,
            CAST(SHIPPINGPROFILEID AS FLOAT) AS SHIPPINGPROFILEID,
            CUSTOMREF1, TOTALCHARGE, USPSPROVIDERTYPE, TRACKINGEVENTLOCATION,
            ORIGINADDRESS1, SHIPTOPOSTALCODE, CAST(CHANNELLINKID AS FLOAT) AS CHANNELLINKID,
            SATURDAYDELIVERYCHARGE, ORIGINADDRESS2, SHIPPEDWEIGHT, SHIPCHARGE,
            ORIGINPOSTALCODE, ORDERNUMBER, DRYICECHARGE,
            CAST(TRACKINGSTATUSID AS FLOAT) AS TRACKINGSTATUSID,
            REFERENCEID, SIGNATUREREQUIREDCHARGE, TRACKINGNUMBER,
            RETURNRECEIPTCHARGE, CREATED_DTTM, DIMHEIGHT,
            DELIVERYCONFIRMATIONCHARGE, LABELTYPE, RESIDENTIALAREACHARGE,
            SHIPTOCONTACT, DIMMEDWEIGHT, MARKETREFERENCE, SHIPTOCOUNTRYCODE,
            HANDLINGCHARGE, ORIGINCOUNTRYCODE, HAZARDOUSMATERIALSCODE,
            CAST(TABLEID AS FLOAT) AS TABLEID, DIMWIDTH, CARRIERVERSIONFLAG,
            BASECARRIERTYPE, ORIGINCOUNTRY, RESTRICTEDDELIVERYCHARGE,
            _FIVETRAN_DELETED, _FIVETRAN_SYNCED, BILLINGACCOUNTNUMBER
        FROM XBPRDWMGOLD.PRD_GOLD_GC_XBWM19WM.DTS_DATA_WAREHOUSE
        --- FIX: This deduplicates the source rows before the MERGE starts ---
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATEDATE DESC, _FIVETRAN_SYNCED DESC) = 1
    ) AS SOURCE
    ON TARGET.ID = SOURCE.ID
    
    WHEN MATCHED AND TARGET.UPDATEDATE < SOURCE.UPDATEDATE 
        THEN UPDATE SET
            TARGET._FIVETRAN_ID = SOURCE._FIVETRAN_ID,
            TARGET.TRACKINGSTATUSLABEL = SOURCE.TRACKINGSTATUSLABEL,
            TARGET.CLOSEID = SOURCE.CLOSEID,
            TARGET.ALTTRACKINGNUMBER = SOURCE.ALTTRACKINGNUMBER,
            TARGET.PACKAGEITEMTOTALQUANTITY = SOURCE.PACKAGEITEMTOTALQUANTITY,
            TARGET.ACCOUNTNUMBER = SOURCE.ACCOUNTNUMBER,
            TARGET.CHANNELID = SOURCE.CHANNELID,
            TARGET.BASECARRIERCODE = SOURCE.BASECARRIERCODE,
            TARGET.CARRIERINSURANCECHARGE = SOURCE.CARRIERINSURANCECHARGE,
            TARGET.MARKETID = SOURCE.MARKETID,
            TARGET.HOST = SOURCE.HOST,
            TARGET.ORIGINCOMPANY = SOURCE.ORIGINCOMPANY,
            TARGET.DIMLENGTH = SOURCE.DIMLENGTH,
            TARGET.ESTIMATEDDELIVERYDATE = SOURCE.ESTIMATEDDELIVERYDATE,
            TARGET.CUSTOMID = SOURCE.CUSTOMID,
            TARGET.SHIPTOADDRESS3 = SOURCE.SHIPTOADDRESS3,
            TARGET.SHIPZONE = SOURCE.SHIPZONE,
            TARGET.SHIPTOADDRESS2 = SOURCE.SHIPTOADDRESS2,
            TARGET.CARRIER = SOURCE.CARRIER,
            TARGET.PACKAGECHARGEATRATING = SOURCE.PACKAGECHARGEATRATING,
            TARGET.SHIPTOADDRESS1 = SOURCE.SHIPTOADDRESS1,
            TARGET.BOXNAME = SOURCE.BOXNAME,
            TARGET.SUBACCOUNTNUMBER = SOURCE.SUBACCOUNTNUMBER,
            TARGET.ORDERID = SOURCE.ORDERID,
            TARGET.STATUS = SOURCE.STATUS,
            TARGET.CARRIERBILLINGTYPE = SOURCE.CARRIERBILLINGTYPE,
            TARGET.SHIPTYPE = SOURCE.SHIPTYPE,
            TARGET.SURCHARGECHARGE = SOURCE.SURCHARGECHARGE,
            TARGET.APPLIEDCHARGETYPE = SOURCE.APPLIEDCHARGETYPE,
            TARGET.USERNAME = SOURCE.USERNAME,
            TARGET.ID = SOURCE.ID,
            TARGET.WORKSTATION = SOURCE.WORKSTATION,
            TARGET.TRACKINGEVENTDATE = SOURCE.TRACKINGEVENTDATE,
            TARGET.CUSTOMREF2 = SOURCE.CUSTOMREF2,
            TARGET.CUSTOMREF3 = SOURCE.CUSTOMREF3,
            TARGET.SHIPTOCITY = SOURCE.SHIPTOCITY,
            TARGET.PRIVATEINSURANCEAMOUNT = SOURCE.PRIVATEINSURANCEAMOUNT,
            TARGET.LASTPRINTDATE = SOURCE.LASTPRINTDATE,
            TARGET.MARKETSHIPMETHOD = SOURCE.MARKETSHIPMETHOD,
            TARGET.DRYICEWEIGHT = SOURCE.DRYICEWEIGHT,
            TARGET.ORDERTYPE = SOURCE.ORDERTYPE,
            TARGET.CREATEDATE = SOURCE.CREATEDATE,
            TARGET.TRACKINGEVENTDESCRIPTION = SOURCE.TRACKINGEVENTDESCRIPTION,
            TARGET.SHIPTOSTATEORPROVINCE = SOURCE.SHIPTOSTATEORPROVINCE,
            TARGET.FUELCHARGE = SOURCE.FUELCHARGE,
            TARGET.ORIGINSTATEORPROVINCE = SOURCE.ORIGINSTATEORPROVINCE,
            TARGET.DEPARTMENT = SOURCE.DEPARTMENT,
            TARGET.PRIVATEINSURANCECHARGE = SOURCE.PRIVATEINSURANCECHARGE,
            TARGET.BATCHID = SOURCE.BATCHID,
            TARGET.DELIVERYAREACHARGE = SOURCE.DELIVERYAREACHARGE,
            TARGET.CURRENCYCODEISO = SOURCE.CURRENCYCODEISO,
            TARGET.STATUSID = SOURCE.STATUSID,
            TARGET.ORIGINCITY = SOURCE.ORIGINCITY,
            TARGET.ACTUALWEIGHT = SOURCE.ACTUALWEIGHT,
            TARGET.ORDERCOUNT = SOURCE.ORDERCOUNT,
            TARGET.CARRIERINSURANCEAMOUNT = SOURCE.CARRIERINSURANCEAMOUNT,
            TARGET.SHIPTOCOMPANY = SOURCE.SHIPTOCOMPANY,
            TARGET.UPDATEDATE = SOURCE.UPDATEDATE,
            TARGET.SHIPROUTE = SOURCE.SHIPROUTE,
            TARGET.SHIPPINGPROFILEID = SOURCE.SHIPPINGPROFILEID,
            TARGET.CUSTOMREF1 = SOURCE.CUSTOMREF1,
            TARGET.TOTALCHARGE = SOURCE.TOTALCHARGE,
            TARGET.USPSPROVIDERTYPE = SOURCE.USPSPROVIDERTYPE,
            TARGET.TRACKINGEVENTLOCATION = SOURCE.TRACKINGEVENTLOCATION,
            TARGET.ORIGINADDRESS1 = SOURCE.ORIGINADDRESS1,
            TARGET.SHIPTOPOSTALCODE = SOURCE.SHIPTOPOSTALCODE,
            TARGET.CHANNELLINKID = SOURCE.CHANNELLINKID,
            TARGET.SATURDAYDELIVERYCHARGE = SOURCE.SATURDAYDELIVERYCHARGE,
            TARGET.ORIGINADDRESS2 = SOURCE.ORIGINADDRESS2,
            TARGET.SHIPPEDWEIGHT = SOURCE.SHIPPEDWEIGHT,
            TARGET.SHIPCHARGE = SOURCE.SHIPCHARGE,
            TARGET.ORIGINPOSTALCODE = SOURCE.ORIGINPOSTALCODE,
            TARGET.ORDERNUMBER = SOURCE.ORDERNUMBER,
            TARGET.DRYICECHARGE = SOURCE.DRYICECHARGE,
            TARGET.TRACKINGSTATUSID = SOURCE.TRACKINGSTATUSID,
            TARGET.REFERENCEID = SOURCE.REFERENCEID,
            TARGET.SIGNATUREREQUIREDCHARGE = SOURCE.SIGNATUREREQUIREDCHARGE,
            TARGET.TRACKINGNUMBER = SOURCE.TRACKINGNUMBER,
            TARGET.RETURNRECEIPTCHARGE = SOURCE.RETURNRECEIPTCHARGE,
            TARGET.CREATED_DTTM = SOURCE.CREATED_DTTM,
            TARGET.DIMHEIGHT = SOURCE.DIMHEIGHT,
            TARGET.DELIVERYCONFIRMATIONCHARGE = SOURCE.DELIVERYCONFIRMATIONCHARGE,
            TARGET.LABELTYPE = SOURCE.LABELTYPE,
            TARGET.RESIDENTIALAREACHARGE = SOURCE.RESIDENTIALAREACHARGE,
            TARGET.SHIPTOCONTACT = SOURCE.SHIPTOCONTACT,
            TARGET.DIMMEDWEIGHT = SOURCE.DIMMEDWEIGHT,
            TARGET.MARKETREFERENCE = SOURCE.MARKETREFERENCE,
            TARGET.SHIPTOCOUNTRYCODE = SOURCE.SHIPTOCOUNTRYCODE,
            TARGET.HANDLINGCHARGE = SOURCE.HANDLINGCHARGE,
            TARGET.ORIGINCOUNTRYCODE = SOURCE.ORIGINCOUNTRYCODE,
            TARGET.HAZARDOUSMATERIALSCODE = SOURCE.HAZARDOUSMATERIALSCODE,
            TARGET.TABLEID = SOURCE.TABLEID,
            TARGET.DIMWIDTH = SOURCE.DIMWIDTH,
            TARGET.CARRIERVERSIONFLAG = SOURCE.CARRIERVERSIONFLAG,
            TARGET.BASECARRIERTYPE = SOURCE.BASECARRIERTYPE,
            TARGET.ORIGINCOUNTRY = SOURCE.ORIGINCOUNTRY,
            TARGET.RESTRICTEDDELIVERYCHARGE = SOURCE.RESTRICTEDDELIVERYCHARGE,
            TARGET._FIVETRAN_DELETED = SOURCE._FIVETRAN_DELETED,
            TARGET._FIVETRAN_SYNCED = SOURCE._FIVETRAN_SYNCED,
            TARGET.BILLINGACCOUNTNUMBER = SOURCE.BILLINGACCOUNTNUMBER
            
    WHEN NOT MATCHED 
        THEN INSERT (
            _FIVETRAN_ID, TRACKINGSTATUSLABEL, CLOSEID, ALTTRACKINGNUMBER,
            PACKAGEITEMTOTALQUANTITY, ACCOUNTNUMBER, CHANNELID,
            BASECARRIERCODE, CARRIERINSURANCECHARGE, MARKETID, HOST,
            ORIGINCOMPANY, DIMLENGTH, ESTIMATEDDELIVERYDATE, CUSTOMID,
            SHIPTOADDRESS3, SHIPZONE, SHIPTOADDRESS2, CARRIER,
            PACKAGECHARGEATRATING, SHIPTOADDRESS1, BOXNAME, SUBACCOUNTNUMBER,
            ORDERID, STATUS, CARRIERBILLINGTYPE, SHIPTYPE, SURCHARGECHARGE,
            APPLIEDCHARGETYPE, USERNAME, ID, WORKSTATION, TRACKINGEVENTDATE,
            CUSTOMREF2, CUSTOMREF3, SHIPTOCITY, PRIVATEINSURANCEAMOUNT,
            LASTPRINTDATE, MARKETSHIPMETHOD, DRYICEWEIGHT, ORDERTYPE,
            CREATEDATE, TRACKINGEVENTDESCRIPTION, SHIPTOSTATEORPROVINCE,
            FUELCHARGE, ORIGINSTATEORPROVINCE, DEPARTMENT,
            PRIVATEINSURANCECHARGE, BATCHID, DELIVERYAREACHARGE,
            CURRENCYCODEISO, STATUSID, ORIGINCITY, ACTUALWEIGHT,
            ORDERCOUNT, CARRIERINSURANCEAMOUNT, SHIPTOCOMPANY, UPDATEDATE,
            SHIPROUTE, SHIPPINGPROFILEID, CUSTOMREF1, TOTALCHARGE,
            USPSPROVIDERTYPE, TRACKINGEVENTLOCATION, ORIGINADDRESS1,
            SHIPTOPOSTALCODE, CHANNELLINKID, SATURDAYDELIVERYCHARGE,
            ORIGINADDRESS2, SHIPPEDWEIGHT, SHIPCHARGE, ORIGINPOSTALCODE,
            ORDERNUMBER, DRYICECHARGE, TRACKINGSTATUSID, REFERENCEID,
            SIGNATUREREQUIREDCHARGE, TRACKINGNUMBER, RETURNRECEIPTCHARGE,
            CREATED_DTTM, DIMHEIGHT, DELIVERYCONFIRMATIONCHARGE, LABELTYPE,
            RESIDENTIALAREACHARGE, SHIPTOCONTACT, DIMMEDWEIGHT,
            MARKETREFERENCE, SHIPTOCOUNTRYCODE, HANDLINGCHARGE,
            ORIGINCOUNTRYCODE, HAZARDOUSMATERIALSCODE, TABLEID, DIMWIDTH,
            CARRIERVERSIONFLAG, BASECARRIERTYPE, ORIGINCOUNTRY,
            RESTRICTEDDELIVERYCHARGE, _FIVETRAN_DELETED, _FIVETRAN_SYNCED,
            BILLINGACCOUNTNUMBER
        )
        VALUES (
            SOURCE._FIVETRAN_ID, SOURCE.TRACKINGSTATUSLABEL, SOURCE.CLOSEID,
            SOURCE.ALTTRACKINGNUMBER, SOURCE.PACKAGEITEMTOTALQUANTITY,
            SOURCE.ACCOUNTNUMBER, SOURCE.CHANNELID, SOURCE.BASECARRIERCODE,
            SOURCE.CARRIERINSURANCECHARGE, SOURCE.MARKETID, SOURCE.HOST,
            SOURCE.ORIGINCOMPANY, SOURCE.DIMLENGTH, SOURCE.ESTIMATEDDELIVERYDATE,
            SOURCE.CUSTOMID, SOURCE.SHIPTOADDRESS3, SOURCE.SHIPZONE,
            SOURCE.SHIPTOADDRESS2, SOURCE.CARRIER, SOURCE.PACKAGECHARGEATRATING,
            SOURCE.SHIPTOADDRESS1, SOURCE.BOXNAME, SOURCE.SUBACCOUNTNUMBER,
            SOURCE.ORDERID, SOURCE.STATUS, SOURCE.CARRIERBILLINGTYPE,
            SOURCE.SHIPTYPE, SOURCE.SURCHARGECHARGE, SOURCE.APPLIEDCHARGETYPE,
            SOURCE.USERNAME, SOURCE.ID, SOURCE.WORKSTATION,
            SOURCE.TRACKINGEVENTDATE, SOURCE.CUSTOMREF2, SOURCE.CUSTOMREF3,
            SOURCE.SHIPTOCITY, SOURCE.PRIVATEINSURANCEAMOUNT,
            SOURCE.LASTPRINTDATE, SOURCE.MARKETSHIPMETHOD, SOURCE.DRYICEWEIGHT,
            SOURCE.ORDERTYPE, SOURCE.CREATEDATE, SOURCE.TRACKINGEVENTDESCRIPTION,
            SOURCE.SHIPTOSTATEORPROVINCE, SOURCE.FUELCHARGE,
            SOURCE.ORIGINSTATEORPROVINCE, SOURCE.DEPARTMENT,
            SOURCE.PRIVATEINSURANCECHARGE, SOURCE.BATCHID,
            SOURCE.DELIVERYAREACHARGE, SOURCE.CURRENCYCODEISO, SOURCE.STATUSID,
            SOURCE.ORIGINCITY, SOURCE.ACTUALWEIGHT, SOURCE.ORDERCOUNT,
            SOURCE.CARRIERINSURANCEAMOUNT, SOURCE.SHIPTOCOMPANY,
            SOURCE.UPDATEDATE, SOURCE.SHIPROUTE, SOURCE.SHIPPINGPROFILEID,
            SOURCE.CUSTOMREF1, SOURCE.TOTALCHARGE, SOURCE.USPSPROVIDERTYPE,
            SOURCE.TRACKINGEVENTLOCATION, SOURCE.ORIGINADDRESS1,
            SOURCE.SHIPTOPOSTALCODE, SOURCE.CHANNELLINKID,
            SOURCE.SATURDAYDELIVERYCHARGE, SOURCE.ORIGINADDRESS2,
            SOURCE.SHIPPEDWEIGHT, SOURCE.SHIPCHARGE, SOURCE.ORIGINPOSTALCODE,
            SOURCE.ORDERNUMBER, SOURCE.DRYICECHARGE, SOURCE.TRACKINGSTATUSID,
            SOURCE.REFERENCEID, SOURCE.SIGNATUREREQUIREDCHARGE,
            SOURCE.TRACKINGNUMBER, SOURCE.RETURNRECEIPTCHARGE,
            SOURCE.CREATED_DTTM, SOURCE.DIMHEIGHT,
            SOURCE.DELIVERYCONFIRMATIONCHARGE, SOURCE.LABELTYPE,
            SOURCE.RESIDENTIALAREACHARGE, SOURCE.SHIPTOCONTACT,
            SOURCE.DIMMEDWEIGHT, SOURCE.MARKETREFERENCE,
            SOURCE.SHIPTOCOUNTRYCODE, SOURCE.HANDLINGCHARGE,
            SOURCE.ORIGINCOUNTRYCODE, SOURCE.HAZARDOUSMATERIALSCODE,
            SOURCE.TABLEID, SOURCE.DIMWIDTH, SOURCE.CARRIERVERSIONFLAG,
            SOURCE.BASECARRIERTYPE, SOURCE.ORIGINCOUNTRY,
            SOURCE.RESTRICTEDDELIVERYCHARGE, SOURCE._FIVETRAN_DELETED,
            SOURCE._FIVETRAN_SYNCED, SOURCE.BILLINGACCOUNTNUMBER
        );
    RETURN ('SUCCESS');
END;