-----| USERS
-- -- Grant role to user
-- GRANT ROLE ROLE_ADMIN_XBOT TO USER ANDREAP;
---------------| START BASIC USER |---------------
-- Creation user
CREATE USER IF NOT EXISTS JLCRUZ
PASSWORD = 'JLCRUZ_12345' 

-- Grant role to user qa
GRANT ROLE QA_ROLE_XBOT TO USER JLCRUZ;
ALTER USER JLCRUZ SET DEFAULT_ROLE =  QA_ROLE_XBOT;

-- Grant role to user prd
GRANT ROLE ROLE_XBOT TO USER JLCRUZ;
ALTER USER JLCRUZ SET DEFAULT_ROLE =  ROLE_XBOT;
---------------| END BASIC USER |---------------

-- Revoke grant role
REVOKE ROLE QA_ROLE_XBOT FROM USER JLCRUZ;


-- REVOKE ROLE SNOWFLAKE_LEARNING_ROLE FROM USER JLCRUZ;
-- Creation role and show grants
CREATE ROLE ROLE_XBOT;
SHOW GRANTS TO ROLE QA_ROLE_XBOT;


--- Grant permissions to old role
GRANT ROLE ROLE_XBOT TO ROLE QA_ROLE_XBOT;

--- PERMISSIONS LEVEL DB, SCHEMA AND VIEWS 

GRANT USAGE ON DATABASE QA_BI TO ROLE ROLE_ADMIN_XBOT;
GRANT USAGE ON SCHEMA QA_BI.WM TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_ORDERS_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_ORDER_LINE_ITEM_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_LPN_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_LPN_DETAIL_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_ITEM_CBO_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_WM_INVENTORY_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_TASK_DTL_ TO ROLE ROLE_ADMIN_XBOT;
GRANT SELECT ON VIEW QA_BI.WM.VW_TASK_HDR_ TO ROLE ROLE_ADMIN_XBOT;


--- CSC USER PERMISSIONS OPERATIONS
GRANT ROLE ROLE_XBOT TO USER CSC_POPSOCKETS;
ALTER USER CSC_POPSOCKETS SET DEFAULT_ROLE =  ROLE_XBOT;
REVOKE ROLE QA_ROLE_XBOT FROM USER CSC_POPSOCKETS;

---- GRANT WAREHOUSE TO ROLE
GRANT USAGE ON WAREHOUSE WHS_XBOT TO ROLE ROLE_ADMIN_XBOT;




